// Code generated by entc, DO NOT EDIT.

package matrixattack

import (
	"time"
)

const (
	// Label holds the string label denoting the matrixattack type in the database.
	Label = "matrix_attack"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdMatrix holds the string denoting the idmatrix field in the database.
	FieldIdMatrix = "id_matrix"
	// FieldVendorName holds the string denoting the vendorname field in the database.
	FieldVendorName = "vendor_name"
	// FieldNameMatrix holds the string denoting the namematrix field in the database.
	FieldNameMatrix = "name_matrix"
	// FieldVersionMatrix holds the string denoting the versionmatrix field in the database.
	FieldVersionMatrix = "version_matrix"
	// FieldCreateDate holds the string denoting the createdate field in the database.
	FieldCreateDate = "create_date"
	// FieldModifyDate holds the string denoting the modifydate field in the database.
	FieldModifyDate = "modify_date"
	// Table holds the table name of the matrixattack in the database.
	Table = "matrix_attacks"
)

// Columns holds all SQL columns for matrixattack fields.
var Columns = []string{
	FieldID,
	FieldIdMatrix,
	FieldVendorName,
	FieldNameMatrix,
	FieldVersionMatrix,
	FieldCreateDate,
	FieldModifyDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultVendorName holds the default value on creation for the "VendorName" field.
	DefaultVendorName string
	// DefaultNameMatrix holds the default value on creation for the "NameMatrix" field.
	DefaultNameMatrix string
	// DefaultVersionMatrix holds the default value on creation for the "VersionMatrix" field.
	DefaultVersionMatrix string
	// DefaultCreateDate holds the default value on creation for the "CreateDate" field.
	DefaultCreateDate func() time.Time
	// DefaultModifyDate holds the default value on creation for the "ModifyDate" field.
	DefaultModifyDate func() time.Time
)
