// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/dreddsa5dies/httprestapient/ent/migrate"

	"github.com/dreddsa5dies/httprestapient/ent/matrixattack"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MatrixAttack is the client for interacting with the MatrixAttack builders.
	MatrixAttack *MatrixAttackClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MatrixAttack = NewMatrixAttackClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		MatrixAttack: NewMatrixAttackClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		MatrixAttack: NewMatrixAttackClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MatrixAttack.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MatrixAttack.Use(hooks...)
}

// MatrixAttackClient is a client for the MatrixAttack schema.
type MatrixAttackClient struct {
	config
}

// NewMatrixAttackClient returns a client for the MatrixAttack from the given config.
func NewMatrixAttackClient(c config) *MatrixAttackClient {
	return &MatrixAttackClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `matrixattack.Hooks(f(g(h())))`.
func (c *MatrixAttackClient) Use(hooks ...Hook) {
	c.hooks.MatrixAttack = append(c.hooks.MatrixAttack, hooks...)
}

// Create returns a create builder for MatrixAttack.
func (c *MatrixAttackClient) Create() *MatrixAttackCreate {
	mutation := newMatrixAttackMutation(c.config, OpCreate)
	return &MatrixAttackCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MatrixAttack entities.
func (c *MatrixAttackClient) CreateBulk(builders ...*MatrixAttackCreate) *MatrixAttackCreateBulk {
	return &MatrixAttackCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MatrixAttack.
func (c *MatrixAttackClient) Update() *MatrixAttackUpdate {
	mutation := newMatrixAttackMutation(c.config, OpUpdate)
	return &MatrixAttackUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MatrixAttackClient) UpdateOne(ma *MatrixAttack) *MatrixAttackUpdateOne {
	mutation := newMatrixAttackMutation(c.config, OpUpdateOne, withMatrixAttack(ma))
	return &MatrixAttackUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MatrixAttackClient) UpdateOneID(id int) *MatrixAttackUpdateOne {
	mutation := newMatrixAttackMutation(c.config, OpUpdateOne, withMatrixAttackID(id))
	return &MatrixAttackUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MatrixAttack.
func (c *MatrixAttackClient) Delete() *MatrixAttackDelete {
	mutation := newMatrixAttackMutation(c.config, OpDelete)
	return &MatrixAttackDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MatrixAttackClient) DeleteOne(ma *MatrixAttack) *MatrixAttackDeleteOne {
	return c.DeleteOneID(ma.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MatrixAttackClient) DeleteOneID(id int) *MatrixAttackDeleteOne {
	builder := c.Delete().Where(matrixattack.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MatrixAttackDeleteOne{builder}
}

// Query returns a query builder for MatrixAttack.
func (c *MatrixAttackClient) Query() *MatrixAttackQuery {
	return &MatrixAttackQuery{
		config: c.config,
	}
}

// Get returns a MatrixAttack entity by its id.
func (c *MatrixAttackClient) Get(ctx context.Context, id int) (*MatrixAttack, error) {
	return c.Query().Where(matrixattack.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MatrixAttackClient) GetX(ctx context.Context, id int) *MatrixAttack {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MatrixAttackClient) Hooks() []Hook {
	return c.hooks.MatrixAttack
}
