// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dreddsa5dies/httprestapient/ent/matrixattack"
	"github.com/dreddsa5dies/httprestapient/ent/predicate"
)

// MatrixAttackQuery is the builder for querying MatrixAttack entities.
type MatrixAttackQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MatrixAttack
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MatrixAttackQuery builder.
func (maq *MatrixAttackQuery) Where(ps ...predicate.MatrixAttack) *MatrixAttackQuery {
	maq.predicates = append(maq.predicates, ps...)
	return maq
}

// Limit adds a limit step to the query.
func (maq *MatrixAttackQuery) Limit(limit int) *MatrixAttackQuery {
	maq.limit = &limit
	return maq
}

// Offset adds an offset step to the query.
func (maq *MatrixAttackQuery) Offset(offset int) *MatrixAttackQuery {
	maq.offset = &offset
	return maq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (maq *MatrixAttackQuery) Unique(unique bool) *MatrixAttackQuery {
	maq.unique = &unique
	return maq
}

// Order adds an order step to the query.
func (maq *MatrixAttackQuery) Order(o ...OrderFunc) *MatrixAttackQuery {
	maq.order = append(maq.order, o...)
	return maq
}

// First returns the first MatrixAttack entity from the query.
// Returns a *NotFoundError when no MatrixAttack was found.
func (maq *MatrixAttackQuery) First(ctx context.Context) (*MatrixAttack, error) {
	nodes, err := maq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{matrixattack.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (maq *MatrixAttackQuery) FirstX(ctx context.Context) *MatrixAttack {
	node, err := maq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MatrixAttack ID from the query.
// Returns a *NotFoundError when no MatrixAttack ID was found.
func (maq *MatrixAttackQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = maq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{matrixattack.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (maq *MatrixAttackQuery) FirstIDX(ctx context.Context) int {
	id, err := maq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MatrixAttack entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one MatrixAttack entity is not found.
// Returns a *NotFoundError when no MatrixAttack entities are found.
func (maq *MatrixAttackQuery) Only(ctx context.Context) (*MatrixAttack, error) {
	nodes, err := maq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{matrixattack.Label}
	default:
		return nil, &NotSingularError{matrixattack.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (maq *MatrixAttackQuery) OnlyX(ctx context.Context) *MatrixAttack {
	node, err := maq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MatrixAttack ID in the query.
// Returns a *NotSingularError when exactly one MatrixAttack ID is not found.
// Returns a *NotFoundError when no entities are found.
func (maq *MatrixAttackQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = maq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = &NotSingularError{matrixattack.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (maq *MatrixAttackQuery) OnlyIDX(ctx context.Context) int {
	id, err := maq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MatrixAttacks.
func (maq *MatrixAttackQuery) All(ctx context.Context) ([]*MatrixAttack, error) {
	if err := maq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return maq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (maq *MatrixAttackQuery) AllX(ctx context.Context) []*MatrixAttack {
	nodes, err := maq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MatrixAttack IDs.
func (maq *MatrixAttackQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := maq.Select(matrixattack.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (maq *MatrixAttackQuery) IDsX(ctx context.Context) []int {
	ids, err := maq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (maq *MatrixAttackQuery) Count(ctx context.Context) (int, error) {
	if err := maq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return maq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (maq *MatrixAttackQuery) CountX(ctx context.Context) int {
	count, err := maq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (maq *MatrixAttackQuery) Exist(ctx context.Context) (bool, error) {
	if err := maq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return maq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (maq *MatrixAttackQuery) ExistX(ctx context.Context) bool {
	exist, err := maq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MatrixAttackQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (maq *MatrixAttackQuery) Clone() *MatrixAttackQuery {
	if maq == nil {
		return nil
	}
	return &MatrixAttackQuery{
		config:     maq.config,
		limit:      maq.limit,
		offset:     maq.offset,
		order:      append([]OrderFunc{}, maq.order...),
		predicates: append([]predicate.MatrixAttack{}, maq.predicates...),
		// clone intermediate query.
		sql:  maq.sql.Clone(),
		path: maq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IdMatrix string `json:"IdMatrix,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MatrixAttack.Query().
//		GroupBy(matrixattack.FieldIdMatrix).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (maq *MatrixAttackQuery) GroupBy(field string, fields ...string) *MatrixAttackGroupBy {
	group := &MatrixAttackGroupBy{config: maq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := maq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return maq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IdMatrix string `json:"IdMatrix,omitempty"`
//	}
//
//	client.MatrixAttack.Query().
//		Select(matrixattack.FieldIdMatrix).
//		Scan(ctx, &v)
//
func (maq *MatrixAttackQuery) Select(fields ...string) *MatrixAttackSelect {
	maq.fields = append(maq.fields, fields...)
	return &MatrixAttackSelect{MatrixAttackQuery: maq}
}

func (maq *MatrixAttackQuery) prepareQuery(ctx context.Context) error {
	for _, f := range maq.fields {
		if !matrixattack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if maq.path != nil {
		prev, err := maq.path(ctx)
		if err != nil {
			return err
		}
		maq.sql = prev
	}
	return nil
}

func (maq *MatrixAttackQuery) sqlAll(ctx context.Context) ([]*MatrixAttack, error) {
	var (
		nodes = []*MatrixAttack{}
		_spec = maq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MatrixAttack{config: maq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, maq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (maq *MatrixAttackQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := maq.querySpec()
	_spec.Node.Columns = maq.fields
	if len(maq.fields) > 0 {
		_spec.Unique = maq.unique != nil && *maq.unique
	}
	return sqlgraph.CountNodes(ctx, maq.driver, _spec)
}

func (maq *MatrixAttackQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := maq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (maq *MatrixAttackQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   matrixattack.Table,
			Columns: matrixattack.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: matrixattack.FieldID,
			},
		},
		From:   maq.sql,
		Unique: true,
	}
	if unique := maq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := maq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matrixattack.FieldID)
		for i := range fields {
			if fields[i] != matrixattack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := maq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := maq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := maq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := maq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (maq *MatrixAttackQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(maq.driver.Dialect())
	t1 := builder.Table(matrixattack.Table)
	columns := maq.fields
	if len(columns) == 0 {
		columns = matrixattack.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if maq.sql != nil {
		selector = maq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if maq.unique != nil && *maq.unique {
		selector.Distinct()
	}
	for _, p := range maq.predicates {
		p(selector)
	}
	for _, p := range maq.order {
		p(selector)
	}
	if offset := maq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := maq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MatrixAttackGroupBy is the group-by builder for MatrixAttack entities.
type MatrixAttackGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (magb *MatrixAttackGroupBy) Aggregate(fns ...AggregateFunc) *MatrixAttackGroupBy {
	magb.fns = append(magb.fns, fns...)
	return magb
}

// Scan applies the group-by query and scans the result into the given value.
func (magb *MatrixAttackGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := magb.path(ctx)
	if err != nil {
		return err
	}
	magb.sql = query
	return magb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := magb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(magb.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := magb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) StringsX(ctx context.Context) []string {
	v, err := magb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = magb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) StringX(ctx context.Context) string {
	v, err := magb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(magb.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := magb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) IntsX(ctx context.Context) []int {
	v, err := magb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = magb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) IntX(ctx context.Context) int {
	v, err := magb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(magb.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := magb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := magb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = magb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) Float64X(ctx context.Context) float64 {
	v, err := magb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(magb.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := magb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := magb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (magb *MatrixAttackGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = magb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (magb *MatrixAttackGroupBy) BoolX(ctx context.Context) bool {
	v, err := magb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (magb *MatrixAttackGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range magb.fields {
		if !matrixattack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := magb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := magb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (magb *MatrixAttackGroupBy) sqlQuery() *sql.Selector {
	selector := magb.sql.Select()
	aggregation := make([]string, 0, len(magb.fns))
	for _, fn := range magb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(magb.fields)+len(magb.fns))
		for _, f := range magb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(magb.fields...)...)
}

// MatrixAttackSelect is the builder for selecting fields of MatrixAttack entities.
type MatrixAttackSelect struct {
	*MatrixAttackQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mas *MatrixAttackSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mas.prepareQuery(ctx); err != nil {
		return err
	}
	mas.sql = mas.MatrixAttackQuery.sqlQuery(ctx)
	return mas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mas *MatrixAttackSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mas.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mas *MatrixAttackSelect) StringsX(ctx context.Context) []string {
	v, err := mas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mas *MatrixAttackSelect) StringX(ctx context.Context) string {
	v, err := mas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mas.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mas *MatrixAttackSelect) IntsX(ctx context.Context) []int {
	v, err := mas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mas *MatrixAttackSelect) IntX(ctx context.Context) int {
	v, err := mas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mas.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mas *MatrixAttackSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mas *MatrixAttackSelect) Float64X(ctx context.Context) float64 {
	v, err := mas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mas.fields) > 1 {
		return nil, errors.New("ent: MatrixAttackSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mas *MatrixAttackSelect) BoolsX(ctx context.Context) []bool {
	v, err := mas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mas *MatrixAttackSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{matrixattack.Label}
	default:
		err = fmt.Errorf("ent: MatrixAttackSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mas *MatrixAttackSelect) BoolX(ctx context.Context) bool {
	v, err := mas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mas *MatrixAttackSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mas.sql.Query()
	if err := mas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
