// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dreddsa5dies/httprestapient/ent/matrixattack"
	"github.com/dreddsa5dies/httprestapient/ent/predicate"
)

// MatrixAttackUpdate is the builder for updating MatrixAttack entities.
type MatrixAttackUpdate struct {
	config
	hooks    []Hook
	mutation *MatrixAttackMutation
}

// Where appends a list predicates to the MatrixAttackUpdate builder.
func (mau *MatrixAttackUpdate) Where(ps ...predicate.MatrixAttack) *MatrixAttackUpdate {
	mau.mutation.Where(ps...)
	return mau
}

// SetIdMatrix sets the "IdMatrix" field.
func (mau *MatrixAttackUpdate) SetIdMatrix(s string) *MatrixAttackUpdate {
	mau.mutation.SetIdMatrix(s)
	return mau
}

// SetVendorName sets the "VendorName" field.
func (mau *MatrixAttackUpdate) SetVendorName(s string) *MatrixAttackUpdate {
	mau.mutation.SetVendorName(s)
	return mau
}

// SetNillableVendorName sets the "VendorName" field if the given value is not nil.
func (mau *MatrixAttackUpdate) SetNillableVendorName(s *string) *MatrixAttackUpdate {
	if s != nil {
		mau.SetVendorName(*s)
	}
	return mau
}

// SetNameMatrix sets the "NameMatrix" field.
func (mau *MatrixAttackUpdate) SetNameMatrix(s string) *MatrixAttackUpdate {
	mau.mutation.SetNameMatrix(s)
	return mau
}

// SetNillableNameMatrix sets the "NameMatrix" field if the given value is not nil.
func (mau *MatrixAttackUpdate) SetNillableNameMatrix(s *string) *MatrixAttackUpdate {
	if s != nil {
		mau.SetNameMatrix(*s)
	}
	return mau
}

// SetVersionMatrix sets the "VersionMatrix" field.
func (mau *MatrixAttackUpdate) SetVersionMatrix(s string) *MatrixAttackUpdate {
	mau.mutation.SetVersionMatrix(s)
	return mau
}

// SetNillableVersionMatrix sets the "VersionMatrix" field if the given value is not nil.
func (mau *MatrixAttackUpdate) SetNillableVersionMatrix(s *string) *MatrixAttackUpdate {
	if s != nil {
		mau.SetVersionMatrix(*s)
	}
	return mau
}

// SetCreateDate sets the "CreateDate" field.
func (mau *MatrixAttackUpdate) SetCreateDate(t time.Time) *MatrixAttackUpdate {
	mau.mutation.SetCreateDate(t)
	return mau
}

// SetNillableCreateDate sets the "CreateDate" field if the given value is not nil.
func (mau *MatrixAttackUpdate) SetNillableCreateDate(t *time.Time) *MatrixAttackUpdate {
	if t != nil {
		mau.SetCreateDate(*t)
	}
	return mau
}

// SetModifyDate sets the "ModifyDate" field.
func (mau *MatrixAttackUpdate) SetModifyDate(t time.Time) *MatrixAttackUpdate {
	mau.mutation.SetModifyDate(t)
	return mau
}

// SetNillableModifyDate sets the "ModifyDate" field if the given value is not nil.
func (mau *MatrixAttackUpdate) SetNillableModifyDate(t *time.Time) *MatrixAttackUpdate {
	if t != nil {
		mau.SetModifyDate(*t)
	}
	return mau
}

// Mutation returns the MatrixAttackMutation object of the builder.
func (mau *MatrixAttackUpdate) Mutation() *MatrixAttackMutation {
	return mau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mau *MatrixAttackUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mau.hooks) == 0 {
		affected, err = mau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MatrixAttackMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mau.mutation = mutation
			affected, err = mau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mau.hooks) - 1; i >= 0; i-- {
			if mau.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mau *MatrixAttackUpdate) SaveX(ctx context.Context) int {
	affected, err := mau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mau *MatrixAttackUpdate) Exec(ctx context.Context) error {
	_, err := mau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mau *MatrixAttackUpdate) ExecX(ctx context.Context) {
	if err := mau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mau *MatrixAttackUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   matrixattack.Table,
			Columns: matrixattack.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: matrixattack.FieldID,
			},
		},
	}
	if ps := mau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mau.mutation.IdMatrix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldIdMatrix,
		})
	}
	if value, ok := mau.mutation.VendorName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldVendorName,
		})
	}
	if value, ok := mau.mutation.NameMatrix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldNameMatrix,
		})
	}
	if value, ok := mau.mutation.VersionMatrix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldVersionMatrix,
		})
	}
	if value, ok := mau.mutation.CreateDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: matrixattack.FieldCreateDate,
		})
	}
	if value, ok := mau.mutation.ModifyDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: matrixattack.FieldModifyDate,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matrixattack.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// MatrixAttackUpdateOne is the builder for updating a single MatrixAttack entity.
type MatrixAttackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MatrixAttackMutation
}

// SetIdMatrix sets the "IdMatrix" field.
func (mauo *MatrixAttackUpdateOne) SetIdMatrix(s string) *MatrixAttackUpdateOne {
	mauo.mutation.SetIdMatrix(s)
	return mauo
}

// SetVendorName sets the "VendorName" field.
func (mauo *MatrixAttackUpdateOne) SetVendorName(s string) *MatrixAttackUpdateOne {
	mauo.mutation.SetVendorName(s)
	return mauo
}

// SetNillableVendorName sets the "VendorName" field if the given value is not nil.
func (mauo *MatrixAttackUpdateOne) SetNillableVendorName(s *string) *MatrixAttackUpdateOne {
	if s != nil {
		mauo.SetVendorName(*s)
	}
	return mauo
}

// SetNameMatrix sets the "NameMatrix" field.
func (mauo *MatrixAttackUpdateOne) SetNameMatrix(s string) *MatrixAttackUpdateOne {
	mauo.mutation.SetNameMatrix(s)
	return mauo
}

// SetNillableNameMatrix sets the "NameMatrix" field if the given value is not nil.
func (mauo *MatrixAttackUpdateOne) SetNillableNameMatrix(s *string) *MatrixAttackUpdateOne {
	if s != nil {
		mauo.SetNameMatrix(*s)
	}
	return mauo
}

// SetVersionMatrix sets the "VersionMatrix" field.
func (mauo *MatrixAttackUpdateOne) SetVersionMatrix(s string) *MatrixAttackUpdateOne {
	mauo.mutation.SetVersionMatrix(s)
	return mauo
}

// SetNillableVersionMatrix sets the "VersionMatrix" field if the given value is not nil.
func (mauo *MatrixAttackUpdateOne) SetNillableVersionMatrix(s *string) *MatrixAttackUpdateOne {
	if s != nil {
		mauo.SetVersionMatrix(*s)
	}
	return mauo
}

// SetCreateDate sets the "CreateDate" field.
func (mauo *MatrixAttackUpdateOne) SetCreateDate(t time.Time) *MatrixAttackUpdateOne {
	mauo.mutation.SetCreateDate(t)
	return mauo
}

// SetNillableCreateDate sets the "CreateDate" field if the given value is not nil.
func (mauo *MatrixAttackUpdateOne) SetNillableCreateDate(t *time.Time) *MatrixAttackUpdateOne {
	if t != nil {
		mauo.SetCreateDate(*t)
	}
	return mauo
}

// SetModifyDate sets the "ModifyDate" field.
func (mauo *MatrixAttackUpdateOne) SetModifyDate(t time.Time) *MatrixAttackUpdateOne {
	mauo.mutation.SetModifyDate(t)
	return mauo
}

// SetNillableModifyDate sets the "ModifyDate" field if the given value is not nil.
func (mauo *MatrixAttackUpdateOne) SetNillableModifyDate(t *time.Time) *MatrixAttackUpdateOne {
	if t != nil {
		mauo.SetModifyDate(*t)
	}
	return mauo
}

// Mutation returns the MatrixAttackMutation object of the builder.
func (mauo *MatrixAttackUpdateOne) Mutation() *MatrixAttackMutation {
	return mauo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mauo *MatrixAttackUpdateOne) Select(field string, fields ...string) *MatrixAttackUpdateOne {
	mauo.fields = append([]string{field}, fields...)
	return mauo
}

// Save executes the query and returns the updated MatrixAttack entity.
func (mauo *MatrixAttackUpdateOne) Save(ctx context.Context) (*MatrixAttack, error) {
	var (
		err  error
		node *MatrixAttack
	)
	if len(mauo.hooks) == 0 {
		node, err = mauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MatrixAttackMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mauo.mutation = mutation
			node, err = mauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mauo.hooks) - 1; i >= 0; i-- {
			if mauo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mauo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mauo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (mauo *MatrixAttackUpdateOne) SaveX(ctx context.Context) *MatrixAttack {
	node, err := mauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mauo *MatrixAttackUpdateOne) Exec(ctx context.Context) error {
	_, err := mauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mauo *MatrixAttackUpdateOne) ExecX(ctx context.Context) {
	if err := mauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mauo *MatrixAttackUpdateOne) sqlSave(ctx context.Context) (_node *MatrixAttack, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   matrixattack.Table,
			Columns: matrixattack.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: matrixattack.FieldID,
			},
		},
	}
	id, ok := mauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MatrixAttack.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matrixattack.FieldID)
		for _, f := range fields {
			if !matrixattack.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != matrixattack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mauo.mutation.IdMatrix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldIdMatrix,
		})
	}
	if value, ok := mauo.mutation.VendorName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldVendorName,
		})
	}
	if value, ok := mauo.mutation.NameMatrix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldNameMatrix,
		})
	}
	if value, ok := mauo.mutation.VersionMatrix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: matrixattack.FieldVersionMatrix,
		})
	}
	if value, ok := mauo.mutation.CreateDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: matrixattack.FieldCreateDate,
		})
	}
	if value, ok := mauo.mutation.ModifyDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: matrixattack.FieldModifyDate,
		})
	}
	_node = &MatrixAttack{config: mauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matrixattack.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
