// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dreddsa5dies/httprestapient/ent/matrixattack"
	"github.com/dreddsa5dies/httprestapient/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	matrixattackFields := schema.MatrixAttack{}.Fields()
	_ = matrixattackFields
	// matrixattackDescVendorName is the schema descriptor for VendorName field.
	matrixattackDescVendorName := matrixattackFields[1].Descriptor()
	// matrixattack.DefaultVendorName holds the default value on creation for the VendorName field.
	matrixattack.DefaultVendorName = matrixattackDescVendorName.Default.(string)
	// matrixattackDescNameMatrix is the schema descriptor for NameMatrix field.
	matrixattackDescNameMatrix := matrixattackFields[2].Descriptor()
	// matrixattack.DefaultNameMatrix holds the default value on creation for the NameMatrix field.
	matrixattack.DefaultNameMatrix = matrixattackDescNameMatrix.Default.(string)
	// matrixattackDescVersionMatrix is the schema descriptor for VersionMatrix field.
	matrixattackDescVersionMatrix := matrixattackFields[3].Descriptor()
	// matrixattack.DefaultVersionMatrix holds the default value on creation for the VersionMatrix field.
	matrixattack.DefaultVersionMatrix = matrixattackDescVersionMatrix.Default.(string)
	// matrixattackDescCreateDate is the schema descriptor for CreateDate field.
	matrixattackDescCreateDate := matrixattackFields[4].Descriptor()
	// matrixattack.DefaultCreateDate holds the default value on creation for the CreateDate field.
	matrixattack.DefaultCreateDate = matrixattackDescCreateDate.Default.(func() time.Time)
	// matrixattackDescModifyDate is the schema descriptor for ModifyDate field.
	matrixattackDescModifyDate := matrixattackFields[5].Descriptor()
	// matrixattack.DefaultModifyDate holds the default value on creation for the ModifyDate field.
	matrixattack.DefaultModifyDate = matrixattackDescModifyDate.Default.(func() time.Time)
}
