// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MatrixAttack is the predicate function for matrixattack builders.
type MatrixAttack func(*sql.Selector)
